<?php

namespace App\Actions;

use App\Models\Game;
use App\Models\GameEvent;

class RecalculateGameState
{
    /**
     * Recalculates the game state by processing all events from the beginning.
     * This allows event editing and deletion without breaking the state.
     */
    public function execute(Game $game): void
    {
        // 1. Reset game state to initial values
        $game->home_score = 0;
        $game->away_score = 0;
        $game->current_inning = 1;
        $game->half_inning = 'top';
        $game->outs = 0;

        $game->first_base_player_id = null;
        $game->second_base_player_id = null;
        $game->third_base_player_id = null;

        $game->save();

        // 2. Fetch all events (except run_scored which are generated by the logic)
        // We will process the raw batting/pitching/fielding events in order.
        $events = GameEvent::where('game_id', $game->id)
            ->where('event_type', '!=', 'run_scored')
            ->orderBy('id', 'asc')
            ->get();

        // 3. Clear run_scored events as they will be re-generated
        // We also need to reset RBI counters on the remaining events.
        GameEvent::where('game_id', $game->id)
            ->where('event_type', 'run_scored')
            ->delete();

        GameEvent::where('game_id', $game->id)
            ->update(['rbi' => 0]);

        // 4. Reprocess each event
        // We need an instance of GameEventController to reuse processEvent logic, 
        // or we move processEvent logic here. For simplicity, we'll instantiate it 
        // or extract the logic. Let's extract the logic here to keep it clean.
        foreach ($events as $event) {
            $this->processEvent($game, $event);

            // Check walk-off
            if (
            $game->current_inning >= 7 &&
            $game->half_inning === 'bottom' &&
            $game->home_score > $game->away_score
            ) {
                if ($game->status != \App\Enums\GameStatus::FINISHED) {
                    $game->status = \App\Enums\GameStatus::FINISHED;
                }
            }

            $game->save();
        }
    }

    private function processEvent(Game $game, GameEvent $event)
    {
        // Actualizar el inning del evento por si se descuadró
        $event->inning = $game->current_inning;
        $event->save();

        $batterId = $event->player_id;
        $batterTeamId = $event->team_id;
        $type = $event->event_type;
        $pitcherId = $event->pitcher_id;

        switch ($type) {
            case 'single':
                $this->advanceRunners($game, $event, $batterId, $batterTeamId, 1, $pitcherId);
                break;
            case 'double':
                $this->advanceRunners($game, $event, $batterId, $batterTeamId, 2, $pitcherId);
                break;
            case 'triple':
                $this->advanceRunners($game, $event, $batterId, $batterTeamId, 3, $pitcherId);
                break;
            case 'homerun':
                $this->advanceRunners($game, $event, $batterId, $batterTeamId, 4, $pitcherId);
                break;
            case 'walk':
            case 'hbp':
                $this->handleWalk($game, $event, $batterId, $batterTeamId, $pitcherId);
                break;
            case 'out':
            case 'strikeout':
                $this->handleOut($game);
                break;
            case 'double_play':
                $this->handleOut($game);
                $this->handleOut($game);
                // Also remove the runner closest to home conceptually, but for now just 2 outs
                break;
        }
    }

    private function handleOut(Game $game)
    {
        $game->outs++;

        if ($game->outs >= 3) {
            $game->outs = 0;
            // limpiar bases
            $game->first_base_player_id = null;
            $game->second_base_player_id = null;
            $game->third_base_player_id = null;

            // cambiar mitad
            if ($game->half_inning === 'top') {
                $game->half_inning = 'bottom';
            }
            else {
                $game->half_inning = 'top';
                $game->current_inning++;
            }
        }
    }

    private function handleWalk(Game $game, GameEvent $event, int $batterId, int $batterTeamId, ?int $pitcherId = null)
    {
        if (
        $game->first_base_player_id &&
        $game->second_base_player_id &&
        $game->third_base_player_id
        ) {
            $this->scoreRun($game);

            GameEvent::create([
                'game_id' => $game->id,
                'team_id' => $batterTeamId,
                'player_id' => $batterId,
                'pitcher_id' => $pitcherId,
                'inning' => $game->current_inning,
                'event_type' => 'run_scored',
                'runs' => 1,
                'rbi' => 0,
                'scored_player_id' => $game->third_base_player_id
            ]);

            $event->update(['rbi' => 1]);

            $game->third_base_player_id = $game->second_base_player_id;
            $game->second_base_player_id = $game->first_base_player_id;
            $game->first_base_player_id = $batterId;
            return;
        }

        if (!$game->first_base_player_id) {
            $game->first_base_player_id = $batterId;
            return;
        }

        if (!$game->second_base_player_id) {
            $game->second_base_player_id = $game->first_base_player_id;
            $game->first_base_player_id = $batterId;
            return;
        }

        if (!$game->third_base_player_id) {
            $game->third_base_player_id = $game->second_base_player_id;
            $game->second_base_player_id = $game->first_base_player_id;
            $game->first_base_player_id = $batterId;
            return;
        }
    }

    private function advanceRunners(Game $game, GameEvent $event, int $batterId, int $batterTeamId, int $bases, ?int $pitcherId = null)
    {
        $runners = [
            3 => $game->third_base_player_id,
            2 => $game->second_base_player_id,
            1 => $game->first_base_player_id
        ];

        $newBases = [1 => null, 2 => null, 3 => null];
        $rbiCount = 0;

        foreach ($runners as $base => $runnerId) {
            if (!$runnerId)
                continue;

            $newPosition = $base + $bases;

            if ($newPosition >= 4) {
                $this->scoreRun($game);
                $rbiCount++;

                GameEvent::create([
                    'game_id' => $game->id,
                    'team_id' => $batterTeamId,
                    'player_id' => $batterId,
                    'pitcher_id' => $pitcherId,
                    'inning' => $game->current_inning,
                    'event_type' => 'run_scored',
                    'runs' => 1,
                    'rbi' => 0,
                    'scored_player_id' => $runnerId
                ]);
            }
            else {
                $newBases[$newPosition] = $runnerId;
            }
        }

        if ($bases >= 4) {
            $this->scoreRun($game);
            $rbiCount++;

            GameEvent::create([
                'game_id' => $game->id,
                'team_id' => $batterTeamId,
                'player_id' => $batterId,
                'pitcher_id' => $pitcherId,
                'inning' => $game->current_inning,
                'event_type' => 'run_scored',
                'runs' => 1,
                'rbi' => 0,
                'scored_player_id' => $batterId
            ]);
        }
        else {
            $newBases[$bases] = $batterId;
        }

        if ($rbiCount > 0) {
            GameEvent::where('id', $event->id)->update(['rbi' => $rbiCount]);
        }

        $game->first_base_player_id = $newBases[1];
        $game->second_base_player_id = $newBases[2];
        $game->third_base_player_id = $newBases[3];
    }

    private function scoreRun(Game $game)
    {
        if ($game->half_inning === 'top') {
            $game->away_score++;
        }
        else {
            $game->home_score++;
        }
    }
}
